# Copyright (c) 2025, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'PR Description Check'
description: 'check if comment exists in PR description'

runs:
  using: "composite"
  steps:
    - name: Get PR description
      id: pr_description
      uses: actions/github-script@v7
      with:
        script: |
          const pr = context.payload.pull_request;
          const prBody = pr.body || '';
          const sha = pr.head.sha;
          const hasComment = prBody.includes('<!--');
          const state = hasComment ? 'failure' : 'success';
          const description = hasComment
            ? 'PR description contains comment in "<!--". Please remove the comment manually.'
            : 'PR description is valid.';

          if (hasComment) {
            core.setFailed(description);
          }

          console.log({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha,
            state,
            target_url: pr.html_url,
            description: description.substring(0, 140),
            context: 'pr-description-check'
          });

          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: sha,
            state: state,
            target_url: pr.html_url,
            description: description.substring(0, 140),
            context: 'pr-description-check'
          });
