# Copyright (c) 2025-2026, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Add to Project"
description: "Add new issue or pull request to the project"
inputs:
  token:
    description: "GitHub token with project write and repository read access"
    required: true
    type: string
  project-url:
    description: "GitHub project URL"
    required: false
    default: 'https://github.com/orgs/NVIDIA/projects/4'

runs:
  using: "composite"
  steps:
    - name: Adding to project
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        PROJECT_URL: ${{ inputs.project-url }}
      run: python3 "${{ github.action_path }}/add_to_project.py"
