# Copyright (c) 2025, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Markdown Link Check'
description: 'Check markdown links'

runs:
  using: "composite"
  steps:
    - name: Run markdown link check
      id: markdown-link-check
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        max-depth: -1
        use-verbose-mode: 'yes'
        base-branch: 'gh-pages'

    - name: Capture and debug action logs
      shell: bash
      run: |
        LOG_CONTENT=$(curl -s -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ github.token }}" \
          "${{ github.server_url }}/repos/${{ github.repository }}/actions/jobs/${{ github.job }}/logs" \
          | awk '/^##\[group\]Run gaurav-nelson\/github-action-markdown-link-check/{flag=1;next}/##\[endgroup\]/{flag=0}flag')
        
        echo "### START OF CAPTURED LOG ###"
        echo "$LOG_CONTENT"
        echo "### END OF CAPTURED LOG ###"
        
        LOG_LENGTH=${#LOG_CONTENT}
        echo "Captured log length: $LOG_LENGTH characters"
        
        echo "LINK_CHECK_LOG<<EOF" >> $GITHUB_ENV
        echo "$LOG_CONTENT" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        