# Copyright (c) 2025, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Markdown Link Check'
description: 'Check markdown links'

runs:
  using: "composite"
  steps:
    - name: Run markdown link check
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        max-depth: -1
        use-verbose-mode: 'yes'
        base-branch: 'gh-pages'
        output-format: json
        output-file: link-results.json

    - name: Show error links summary
      if: always()
      run: |
        echo -e "\n\n### Error Links Summary ###"        
        grep -B 1 '"status": [^2]' link-results.json | \
        awk '
          /"link":/ {
            gsub(/^[ \t]+"link": "/, "", $0);
            gsub(/",?$/, "", $0);
            link = $0
          }
          /"status":/ {
            status = $2
            sub(/,/, "", status);
          }
          /"filename":/ {
            gsub(/^[ \t]+"filename": "/, "", $0);
            gsub(/",?$/, "", $0);
            if (link != "" && status != "" && $0 != "") {
              printf "[%s] %-60s => %s\n", status, link, $0
              link = ""; status = ""
            }
          }
        ' | sort -u
        
        echo "### Total broken links: $(grep -c '"status": [^2]' link-results.json)"